# Generated by Django 3.2.9 on 2021-12-10 20:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='_users_userprofile_followers_+', to=settings.AUTH_USER_MODEL),
        ),
    ]
