# Generated by Django 3.2.9 on 2021-11-09 18:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('network', '0002_post_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='Imagenes_del_sitio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('title', models.CharField(default='Título', max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(default='Título', max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='network_post', to=settings.AUTH_USER_MODEL),
        ),
    ]
